### ISSUE TITLE
Run command with Maven properties

### ISSUE THREAD

**Issue by blackat** [wildfly/wildfly-maven-plugin#69] opened 2015-10-07 06:19 UTC
Hi,
I have tried to run some commands before deploying an application during the `wildfly:run` goal with some Maven properties in order to add for instance a data source

```xml
<beforeDeployment>
        <commands>
            <batch>false</batch>
            <command>
                data-source add --jndi-name=${hibernate.datasource.jndi.name} ...
            </command>
        </commands>
    </beforeDeployment>
```

but the maven properties are not filtered so the command fails. I have seen you can use a property file when you run the ``jboss-cli.bat` but I do not know how to specify it and moreover I would like to use some Maven default properties coming from the IDE configuration (I use Idea and I can specify properties in the Maven Runner settings).

Is there a way to do? is it an enhancement of the plugin?

Thanks a lot for your time.

**Comment by jamezp** [comment] 2015-10-08 21:18
The problem is using properties like that is a valid value for some attributes. Knowing when to resolve the property in maven vs send the expression to with the command would be a best guess.

**Comment by ssaarinen** [comment] 2015-12-11 08:28
+1 for this.
Could eg. escaping be used to mark when resolving should (not) be done by maven or with some additional cfg like below to remain backwards compatible? 
```
<expandPropertiesAnchor>#<expandPropertiesAnchor>
<command>
    data-source add --jndi-name=#{hibernate.datasource.jndi.name} ...
</command>
```

**Comment by sventorben** [comment] 2015-12-11 18:52
Why not using a script instead of commands and have maven filter the script file with default maven resource filtering?

http://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html

**Comment by ssaarinen** [comment] 2015-12-12 14:26
Have to try that one!

**Comment by jamezp** [comment] 2015-12-14 22:41
I prefer the script + resource filtering approach @sventorben suggests. I think adding a a separate syntax could be confusing.

I'm closing this issue as I think the script + resource filtering is a sufficient workaround.

**Closed by jamezp** 2015-12-14 22:41 UTC
